// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHIpKPOHJfWjsk3Ik2j70VR7aZOKWhvaU',
    appId: '1:931948020920:web:9264f8186f9df78038a04d',
    messagingSenderId: '931948020920',
    projectId: 'fir-demo-e7048',
    authDomain: 'fir-demo-e7048.firebaseapp.com',
    storageBucket: 'fir-demo-e7048.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf8Wkuw2OFJxLLWrVq5mQinhQMTSKN4JM',
    appId: '1:931948020920:android:f712b73693345b6438a04d',
    messagingSenderId: '931948020920',
    projectId: 'fir-demo-e7048',
    storageBucket: 'fir-demo-e7048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnB0cLLmNLBZ3buEHqOei0_FQCOko6l0s',
    appId: '1:931948020920:ios:a9726b973607bf3d38a04d',
    messagingSenderId: '931948020920',
    projectId: 'fir-demo-e7048',
    storageBucket: 'fir-demo-e7048.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnB0cLLmNLBZ3buEHqOei0_FQCOko6l0s',
    appId: '1:931948020920:ios:a9726b973607bf3d38a04d',
    messagingSenderId: '931948020920',
    projectId: 'fir-demo-e7048',
    storageBucket: 'fir-demo-e7048.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHIpKPOHJfWjsk3Ik2j70VR7aZOKWhvaU',
    appId: '1:931948020920:web:f584d4bea180987b38a04d',
    messagingSenderId: '931948020920',
    projectId: 'fir-demo-e7048',
    authDomain: 'fir-demo-e7048.firebaseapp.com',
    storageBucket: 'fir-demo-e7048.firebasestorage.app',
  );

}